services:
    dmzx.totalattdownloaded.listener:
        class: dmzx\totalattdownloaded\event\listener
        arguments:
            - @template
            - @user
            - @dbal.conn
        tags:
            - { name: event.listener }
